<?php 
/**
 * ZF2 Buch Kapitel 16
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Blog
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * namespace definition and usage
 */
use Blog\Entity\BlogEntity;

/**
 * Blog index view script
 * 
 * @package    Blog
 */

$this->headTitle('Luigis Pizza-Blog');
$this->pageTitle('Luigis Pizza-Blog');
?>
<?php foreach ($this->blogList as $blog) : /* @var $blog BlogEntity */ ?>
<?php
$urlShow = $this->url('blog/action', array('url' => $blog->getUrl()));
?>
<h3><?php echo $blog->getTitle(); ?></h3>
<p><em>Datum: <?php echo $this->date($blog->getCdate()); ?></em></p>
<div class="clearfix">
<?php echo $blog->getTeaser(); ?>
<p><a href="<?php echo $urlShow; ?>" class="btn">Weiter lesen</a></p>
</div>
<hr />
<?php endforeach; ?>
<?php
echo $this->paginationControl(
    $this->blogList, 'Sliding', 'pagination/sliding', 
    array('route' => 'blog/page')
);
?>
<p class="pull-center">
<?php $url = $this->url('blog-admin'); ?>
<a href="<?php echo $url; ?>" class="btn">Blogbeiträge verwalten</a>
</p>
