<?php 
/**
 * ZF2 Buch Kapitel 16
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Blog
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * namespace definition and usage
 */
use Blog\Entity\BlogEntity;

/**
 * Blog show view script
 * 
 * @package    Blog
 */

$blog = $this->blogData;  /* @var $blog BlogEntity */

$this->headTitle($blog->getTitle());
$this->pageTitle($blog->getTitle());
?>
<p><em>Datum: <?php echo $this->date($blog->getCdate()); ?></em></p>
<?php echo $blog->getContent(); ?>
<p><a href="<?php echo $this->url('blog'); ?>" class="btn">Zurück</a></p>
