<?php 
/**
 * ZF2 Buch Kapitel 16
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 16.27 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 16.27');
$this->pageTitle('Listing 16.27');
?>
<h3><code>BlogController</code> für öffentlichen Bereich</h3>
<pre>
&lt;?php
namespace Blog\Controller;

use Zend\Feed\Writer\Feed;
use Zend\View\Model\FeedModel;
use Zend\View\Model\ViewModel;
use Zend\Mvc\Controller\AbstractActionController;
use Blog\Service\BlogServiceInterface;

class BlogController extends AbstractActionController
{
    protected $blogService;
    
    public function setBlogService(BlogServiceInterface $blogService)
    {
        $this->blogService = $blogService;

        return $this;
    }
    
    public function getBlogService()
    {
        return $this->blogService;
    }
    
    public function indexAction()
    {
        // read page from route
        $page = (int) $this->params()->fromRoute('page');
        
        // set max blog per page
        $maxPage = 10;
        
        // read data and pass to view
        return new ViewModel(array(
            'blogList' => $this->getBlogService()->fetchList($page, $maxPage),
        ));
    }
    
    public function showAction()
    {
        // read url from route
        $url = $this->params()->fromRoute('url');
        
        // fetch data
        $blogData = $this->getBlogService()->fetchSingleByUrl($url);
        
        // check data
        if (!$blogData) {
            // Redirect to blog page
            return $this->redirect()->toRoute('blog');
        }
        
        // read data and pass to view
        return new ViewModel(array(
            'blogData' => $blogData,
        ));
    }
    
    public function rssAction()
    {
        // set page and max blog per page
        $page    = 1;
        $maxPage = 10;
        
        // get blog entries
        $blogList = $this->getBlogService()->fetchList($page, $maxPage);
        
        // create feed
        $feed = new Feed();
        $feed->setTitle('Luigis Pizza-Blog');
        $feed->setFeedLink('http://luigis-pizza.local/blog/rss', 'atom');
        $feed->addAuthor(array(
            'name'  => 'Luigi Bartoli',
            'email' => 'luigi@luigis-pizza.de',
            'uri'   => 'http://luigis-pizza.local',
        ));
        $feed->setDescription('Luigis Pizza-Blog Beiträge');
        $feed->setLink('http://luigis-pizza.local');
        $feed->setDateModified(time());
        
        // add blog entries
        foreach ($blogList as $blog) {
            $entry = $feed->createEntry();
            $entry->setTitle($blog->getTitle());
            $entry->setLink('http://luigis-pizza.local/blog/' . $blog->getUrl());
            $entry->setDescription($blog->getContent());
            $entry->setDateCreated(strtotime($blog->getCdate()));
            
            $feed->addEntry($entry);
        }
        
        // create feed model
        $feedmodel = new FeedModel();
        $feedmodel->setFeed($feed);
        
        return $feedmodel;
    }
}
</pre>
