<?php 
/**
 * ZF2 Buch Kapitel 16
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 16.5 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 16.5');
$this->pageTitle('Listing 16.5');
?>
<h3><code>BlogController</code> für <code>Blog</code> Modul</h3>
<pre>
&lt;?php
namespace Blog\Controller;

use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;

class BlogController extends AbstractActionController
{
    public function indexAction()
    {
        return new ViewModel(array('params' => $this->params()->fromRoute()));
    }
    
    public function showAction()
    {
        return new ViewModel(array('params' => $this->params()->fromRoute()));
    }
    
    public function rssAction()
    {
        return new ViewModel(array('params' => $this->params()->fromRoute()));
    }
}
</pre>
