<?php 
/**
 * ZF2 Buch Kapitel 16
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 16.35 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 16.35');
$this->pageTitle('Listing 16.35');
?>
<h3>Löschen eines Blogbeitrags mit <code>delete.phtml</code></h3>
<pre>
&lt;?php
$this-&gt;headTitle('Blogbeitrag löschen');
$this-&gt;pageTitle('Den ausgewählten Blogbeitrag löschen');
?&gt;
&lt;table class="table table-data"&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;th&gt;Überschrift:&lt;/th&gt;
&lt;td&gt;&lt;?php echo $blog-&gt;getTitle(); ?&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;th&gt;Anreißer:&lt;/th&gt;
&lt;td&gt;&lt;?php echo $blog-&gt;getTeaser(); ?&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;th&gt;Datum:&lt;/th&gt;
&lt;td&gt;&lt;?php echo $this-&gt;date($blog-&gt;getCdate()); ?&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;?php 
$actionUrl = $this-&gt;url('blog-admin/action', array(), array(), true);
echo $this-&gt;showForm($this-&gt;form, $actionUrl, 'form-horizontal');
?&gt; 
</pre>
