<?php 
/**
 * ZF2 Buch Kapitel 16
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 16.12 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 16.12');
$this->pageTitle('Listing 16.12');
?>
<h3><code>BlogTableInterface</code> für Tabelle <code>blogs</code></h3>
<pre>
&lt;?php
namespace Blog\Table;

use Blog\Entity\BlogEntityInterface;
use Zend\Db\Adapter\Adapter;
use Zend\Db\TableGateway\TableGatewayInterface;

interface BlogTableInterface extends TableGatewayInterface
{
    public function __construct(Adapter $adapter, BlogEntityInterface $entity);
    public function fetchSingleByUrl($url);
    public function fetchSingleById($id);
}
</pre>
