<?php 
/**
 * ZF2 Buch Kapitel 16
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 16.20 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 16.20');
$this->pageTitle('Listing 16.20');
?>
<h3>Weitere Factories für die Initialisierung von Formularen</h3>
<pre>
&lt;?php
namespace Blog\Form;

use Blog\Filter\BlogFilter;
use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;

class UpdateFormFactory implements FactoryInterface
{
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $form = new BlogForm('update');
        $form->addIdElement();
        $form->addCsrfElement();
        $form->addTitleElement();
        $form->addTeaserElement();
        $form->addContentElement();
        $form->addSubmitElement('save', 'Speichern');
        $form->addSubmitElement('cancel', 'Abbrechen');
        $form->setInputFilter(new BlogFilter());
        $form->setValidationGroup(
            array('id', 'title', 'teaser', 'content', 'save', 'cancel')
        );
        return $form;
    }
}

class DeleteFormFactory implements FactoryInterface
{
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $form = new BlogForm('delete');
        $form->addIdElement();
        $form->addCsrfElement();
        $form->addSubmitElement('delete', 'Löschen');
        $form->addSubmitElement('cancel', 'Abbrechen');
        $form->setInputFilter(new BlogFilter());
        $form->setValidationGroup(array('id', 'delete', 'cancel'));
        return $form;
    }
}
</pre>
