<?php 
/**
 * ZF2 Buch Kapitel 16
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 16.9 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 16.9');
$this->pageTitle('Listing 16.9');
?>
<h3>Datenbankkonfiguration in <code>/config/autoload/local.php</code></h3>
<pre>
&lt;?php
return array(
    'db' => array(
        'driver'   => 'Pdo_Sqlite',
        'database' => LUIGI_ROOT . '/data/db/luigi.sqlite3.db',
    ),
);
</pre>
