<?php 
/**
 * ZF2 Buch Kapitel 16
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 16.8 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 16.8');
$this->pageTitle('Listing 16.8');
?>
<h3>Datenbankkonfiguration in <code>/config/autoload/global.php</code></h3>
<pre>
&lt;?php
return array(
    'service_manager' => array(
        'factories' => array(
            'Zend\Db\Adapter\Adapter' => 'Zend\Db\Adapter\AdapterServiceFactory',
        ),
    ),
);
</pre>
