<?php 
/**
 * ZF2 Buch Kapitel 16
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 16.33 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 16.33');
$this->pageTitle('Listing 16.33');
?>
<h3>Anlegen eines neuen Blogbeitrags mit <code>create.phtml</code></h3>
<pre>
&lt;?php
$this->headTitle('Blogbeitrag anlegen');
$this->pageTitle('Einen neuen Blogbeitrag anlegen');

$this->headScript()->appendFile(
    $this->basePath() . '/js/ckeditor/ckeditor.js', 'text/javascript'
);

$actionUrl = $this->url('blog-admin/action', array('action' => 'create'));

echo $this->showForm($this->form, $actionUrl, 'form-horizontal');
</pre>
