<?php 
/**
 * ZF2 Buch Kapitel 16
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 16.7 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 16.7');
$this->pageTitle('Listing 16.7');
?>
<h3>Aufbau der Datenbanktabelle</h3>
<pre>
CREATE TABLE blogs (
    id integer primary key, 
    cdate datetime, 
    title varchar(128), 
    teaser text, 
    content text, 
    url varchar(128)
);
</pre>
