<?php 
/**
 * ZF2 Buch Kapitel 16
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 16.7 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 16.7');
$this->pageTitle('Listing 16.7');
?>
<h3>Aufbau der Datenbanktabelle</h3>
<pre>
CREATE TABLE blogs (
    id integer primary key, 
    cdate datetime, 
    title varchar(128), 
    teaser text, 
    content text, 
    url varchar(128)
);
</pre>
