<?php 
/**
 * ZF2 Buch Kapitel 16
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 16.22 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 16.22');
$this->pageTitle('Listing 16.22');
?>
<h3>Geänderte <code>Module.php</code> für Injizierung der <code>BlogForm</code>-Objekte</h3>
<pre>
&lt;?php
namespace Blog;

use Zend\EventManager\EventInterface;
use Zend\ModuleManager\Feature\AutoloaderProviderInterface;
use Zend\ModuleManager\Feature\BootstrapListenerInterface;
use Zend\ModuleManager\Feature\ConfigProviderInterface;
use Zend\ServiceManager\ServiceLocatorInterface;

class Module implements 
    BootstrapListenerInterface,
    ConfigProviderInterface, 
    AutoloaderProviderInterface
{
    protected $serviceLocator = null;
    
    public function onBootstrap(EventInterface $e)
    {
        // set service locator
        $this->serviceLocator = $e->getApplication()->getServiceManager();
        
        // get shared event manager
        $sharedEventManager = $this->serviceLocator->get('SharedEventManager');
        
        // add form event
        $sharedEventManager->attach(
            'Blog\Service\BlogService', 
            'set-blog-form', 
            array($this, 'onFormSet')
        );
    }
    
    [...]
    
    public function onFormSet(EventInterface $e)
    {
        $type = $e->getParam('type', 'create');
        $service = $this->serviceLocator->get('Blog\Service\Blog');
        $form    = $this->serviceLocator->get('Blog\Form\\' . ucfirst($type));
        $service->setForm($form, $type);
    }
}
</pre>
