<?php 
/**
 * ZF2 Buch Kapitel 16
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 16.6 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 16.6');
$this->pageTitle('Listing 16.6');
?>
<h3>View-Skript <code>index.phtml</code> für <code>Blog</code> Modul</h3>
<pre>
&lt;?php
$this->headTitle('Controller "' . $this->params['controller'] . '"');
$this->pageTitle('Controller "' . $this->params['controller'] . '"');
?&gt;
&lt;h3&gt;Action "&lt;?php echo $this-&gt;params['action']; ?&gt;"&lt;/h3&gt;
&lt;p&gt;Alle Parameter:&lt;/p&gt;
&lt;ul&gt;
&lt;?php foreach ($this-&gt;params as $key =&gt; $param) :?&gt;
&lt;li&gt;&lt;?php echo $key; ?&gt; =&gt; &lt;?php echo $param; ?&gt;&lt;/li&gt;
&lt;?php endforeach; ?&gt;
&lt;/ul&gt;
</pre>
