<?php 
/**
 * ZF2 Buch Kapitel 16
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 16.28 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 16.28');
$this->pageTitle('Listing 16.28');
?>
<h3>Konfiguration der View-Strategy im View-Manager</h3>
<pre>
&lt;?php
return array(
    [...]
    
    'view_manager' => array(
        [...]
        'strategies' => array(
            'ViewFeedStrategy',
        ),
    ),
    
    [...]
);
</pre>
