<?php 
/**
 * ZF2 Buch Kapitel 16
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 16.15 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 16.15');
$this->pageTitle('Listing 16.15');
?>
<h3>Modifizierte <code>module.config.php</code> mit Service-Manager Konfiguration</h3>
<pre>
&lt;?php
return array(
    [...]
    
    'service_manager' => array(
        'invokables' => array(
            'Blog\Entity\Blog' => 'Blog\Entity\BlogEntity',
        ),
        'factories' => array(
            'Blog\Table\Blog' => 'Blog\Table\BlogTableFactory',
        ),
    ),
    
    [...]
);
</pre>
